In [1]:
import numpy as np

# Array Operations
1: Arithmetic Operations

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [3]:
sum = arr1 + arr2
sum

array([ 7,  9, 11, 13, 15])

In [4]:
sub = arr2 - arr1
sub

array([5, 5, 5, 5, 5])

In [5]:
mult = arr1 * arr2
mult

array([ 6, 14, 24, 36, 50])

In [6]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [8]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

2: Broadcasting

In [9]:
l = [1,2,3,4,5]
arr = np.array(l)

In [10]:
arr = arr + 10
arr

array([11, 12, 13, 14, 15])

2: Broadcasting

   |-- Deep and Shallow Copy

In [11]:
arr = np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [12]:
slice = arr[4:10]
slice

array([ 5,  6,  7,  8,  9, 10])

In [13]:
slice = slice + 10
slice

array([15, 16, 17, 18, 19, 20])

In [14]:
arr
arr2 = arr.copy()

In [15]:
arr2[6] = 90

In [16]:
arr2

array([ 1,  2,  3,  4,  5,  6, 90,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

3: Matrix Operations

In [18]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [19]:
mat1

array([[1, 2],
       [3, 4]])

In [20]:
mat2

array([[5, 6],
       [7, 8]])

In [21]:
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [22]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [23]:
mat1.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation
1: Stacking Array

In [24]:
mat1 = np.array([1,2,3,4])
mat2 = np.array([5,6,7,8])

In [25]:
mat1

array([1, 2, 3, 4])

In [26]:
mat2

array([5, 6, 7, 8])

In [27]:
np.vstack((mat1,mat2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
np.hstack((mat1,mat2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np.column_stack((mat1,mat2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

2: Splitting Array

In [34]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [36]:
np.hsplit(a,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [37]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [39]:
split = np.vsplit(a,4)
split

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [40]:
for i in split:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
