In [1]:
import numpy as np

# Numpy Array Creation

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
l = (1,2,3.5,'Hello')
l

(1, 2, 3.5, 'Hello')

In [4]:
np.array(l)

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [18]:
arr = np.linspace(1,6,3)
arr

array([1. , 3.5, 6. ])

In [19]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Random Generation Functions

In [20]:
np.random.rand(10)

array([0.80041732, 0.85946929, 0.85915907, 0.82121502, 0.30348636,
       0.61733086, 0.85833906, 0.24125261, 0.94799306, 0.08654535])

In [29]:
np.random.randn(5)

array([ 1.25178076, -1.04515445, -0.79694821, -1.19372973,  0.35254148])

In [34]:
np.random.randint(5,10,2)

array([7, 6], dtype=int32)

# Array Attributes

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

In [45]:
arr.min()

np.int64(1)

In [46]:
arr.max()

np.int64(9)

In [47]:
arr.sum()

np.int64(45)

In [48]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [49]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [50]:
arr.mean()

np.float64(5.0)

In [51]:
arr.std()

np.float64(2.581988897471611)

In [52]:
arr.argmin()

np.int64(0)

In [53]:
arr.argmax()

np.int64(8)

# Reshaping and Resizing

In [55]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [59]:
arr = arr.reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])