In [3]:
import numpy as np

# Numpy Indexing and Slicing of Vectors

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[6]

np.int64(7)

In [6]:
arr[2:7]

array([3, 4, 5, 6, 7])

In [7]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr_slice = arr[::3]
arr_slice

array([ 1,  4,  7, 10])

# Numpy Indexing and Slicing of Matrix

In [9]:
arr = np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [10]:
arr[0]

array([1, 2, 3, 4])

In [11]:
arr[0,0]

np.int64(1)

In [12]:
arr[2,2]

np.int64(11)

In [13]:
slice = arr[2:4,2:4]
slice

array([[11, 12],
       [15, 16]])

In [14]:
slice = arr[3:,2:]
slice

array([[15, 16],
       [19, 20]])

In [20]:
slice = arr[:,2]
slice

array([ 3,  7, 11, 15, 19])

In [21]:
slice = arr[2,:]
slice

array([ 9, 10, 11, 12])

# Boolean Indexing

In [22]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [25]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])