In [1]:
import numpy as np

# Valid Sudoku

In [2]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [3]:
a = np.sum(s,axis = 1)
for i in a:
    if i != 45:
        print("Sudoku isn't valid")
        break
    else:
        print("For rows the Sudoku is valid")
        break

For rows the Sudoku is valid


In [4]:
b = np.sum(s,axis = 0)
for i in b:
    if i != 45:
        print("Sudoku isn't valid")
        break
    else:
        print("For Columns the Sudoku is valid")
        break

For Columns the Sudoku is valid


In [5]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


# General Questions

In [6]:
# Columns: Age, Math Marks, Science Marks
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [7]:
# Get the shape of the matrix
data.shape

(5, 3)

In [8]:
# Find the average age of Students
slice = data[:,0]
slice

array([18, 19, 17, 18, 20])

In [9]:
sum = slice.sum()
average = sum / 5
average

np.float64(18.4)

In [10]:
np.mean(data[:,0])

np.float64(18.4)

In [11]:
#Extract the Math marks of all Students
slice = data[:,1]
slice

array([85, 92, 76, 65, 90])

In [12]:
#Find the highest Science marks
np.max(data[2])

np.int64(95)

In [13]:
# Get details of the Students who scored higher than 90 in Math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [14]:
# Increase the Math marks of the Students by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [15]:
# Find how many students are younger than 18
slice = data[:,0]
for i in slice:
    if i < 19:
        print("Student younger than 18 is",i)

Student younger than 18 is 18
Student younger than 18 is 17
Student younger than 18 is 18


In [16]:
len(data[data[:,0] < 19])

3

In [17]:
# Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:], axis = 0)

array([86.6, 83.2])

In [18]:
np.mean(data[:,2])

np.float64(83.2)

In [19]:
# Get the data of Students who scored at least 80 in both subjects

data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [20]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [23]:
# Replace all Sciene marks less than 75 with 0

data[data[:,2] < 75]
data[0,2] = 0
data


array([[18, 90,  0],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])